---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tgtubechan
data:
  YamlConfigPath: "{{ $.Values.YamlConfigPath }}"
  KvToken: "{{ $.Values.KvToken }}"
  KvAccountId: "{{ $.Values.KvAccountId }}"
  KvNamespaceId: "{{ $.Values.KvNamespaceId }}"
  TgToken: "{{ $.Values.TgToken }}"
  TgBossChatId: "{{ $.Values.TgBossChatId }}"

