---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tgtubechan
  labels:
    app: tgtubechan
spec:
  selector:
    matchLabels:
      app: tgtubechan
  template:
    metadata:
      name: tgtubechan
      labels:
        app: tgtubechan
    spec:
      containers:
        - name: tgtubechan
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageName }}:{{ $.Values.ImageTag }}"
          envFrom:
            - configMapRef:
                name: tgtubechan

