---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ $.Release.Name }}-tgtubechan
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-tgtubechan

spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-tgtubechan
  template:
    metadata:
      name: {{ $.Release.Name }}-tgtubechan
      labels:
        app: {{ $.Release.Name }}-tgtubechan
      annotations:
        checksum/configmap: {{ include ( print $.Template.BasePath "/" "configmap.yaml" ) . | sha256sum }}

    spec:

      containers:

        - name: {{ $.Release.Name }}-tgtubechan
          image: "{{ $.Values.ImageNameGithubTgTubeChan }}:{{ $.Values.ImageTagGithubTgTubeChan }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-tgtubechan


