---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-tgtubechan
  labels:
    app: {{ $.Release.Name }}-tgtubechan
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-tgtubechan
  template:
    metadata:
      name: {{ $.Release.Name }}-tgtubechan
      labels:
        app: {{ $.Release.Name }}-tgtubechan
    spec:
      containers:
        - name: {{ $.Release.Name }}-tgtubechan
          imagePullPolicy: IfNotPresent
          image: "{{ $.Values.ImageNameTgTubeChan }}:{{ $.Values.ImageTagTgTubeChan }}"
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-tgtubechan

