---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ $.Values.AppName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Values.AppName }}

spec:

  selector:
    matchLabels:
      app: {{ $.Values.AppName }}

  template:
    metadata:
      name: {{ $.Values.AppName }}
      labels:
        app: {{ $.Values.AppName }}
      annotations:
        checksum/configmap: {{ include ( print $.Template.BasePath "/" "configmap.yaml" ) . | sha256sum }}

    spec:

      containers:

        - name: {{ $.Values.AppName }}
          image: "{{ $.Values.ImageNameGithubTgTubeChan }}:{{ $.Values.ImageTagGithubTgTubeChan }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ $.Values.AppName }}


