apiVersion: v2
name: helm.tgytchan
description: Mirror a Youtube channel to a Telegram channel
type: application
version: __VERSION__
appVersion: __VERSION__
home: https://github.com/shoce/tgytchan/tree/main/helm/

