---

DEBUG: false

YamlConfigPath: tgtubechan.yaml

Interval: 51m

KvToken: ""
KvAccountId: ""
KvNamespaceId: ""

TgToken: ""
TgBossChatId: ""

ImageNameTgTubeChan: ghcr.io/shoce/tgtubechan
ImageTagTgTubeChan: ""


